spring:
  redis:
    database: 1
    host: 127.0.0.1
  application:
    name: r-pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/r_pan?characterEncoding=utf8&serverTimeZone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        testInput:
          destination: testTopic
          group: testTopicGroup1
        testOutput:
          destination: testTopic
        errorLogInput:
          destination: errorLogTopic
          group: errorLogGroup
        deleteFileInput:
          destination: deleteFileTopic
          group: deleteFileGroup
        fileRestoreInput:
          destination: fileRestoreTopic
          group: fileRestoreGroup
        physicalDeleteFileInput:
          destination: physicalDeleteFileTopic
          group: physicalDeleteFileGroup
        userSearchInput:
          destination: userSearchTopic
          group: userSearchGroup
        errorLogOutput:
          destination: errorLogTopic
        deleteFileOutput:
          destination: deleteFileTopic
        fileRestoreOutput:
          destination: fileRestoreTopic
        physicalDeleteFileOutput:
          destination: physicalDeleteFileTopic
        userSearchOutput:
          destination: userSearchTopic


mybatis-plus:
  mapper-locations: classpath:mappers/**/*/*.xml

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans


swagger2:
  show: false
  group-name: ${spring.application.name}
  base-package: com.imooc.pan
  title: r-pan-server docs
  description: r-pan-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: Ian
  contact-url: https://github.com/IanZC0der
  contact-email: ianzhangbc@outlook.com
  version: 1.0

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: INFO
#com:
#  imooc:
#    pan:
#      storage:
#        engine:
#          gcs:
#            bucket-name: "drive-harbor-test"
#            project-id: "cloud-zhang-benchi2"
#            credentials-path: "/Users/benchi/Downloads/cloud-zhang-benchi2-2655a444063c.json"


#com:
#  imooc:
#    pan:
#      storage:
#        engine:
#          oss:
#            bucket-name: driveharbor-testt
#            endpoint: oss-us-east-1.aliyuncs.com
com:
  imooc:
    pan:
#      storage:
#        engine:
#          oss:
#            bucket-name: driveharbor-testt
#            endpoint: oss-us-east-1.aliyuncs.com
#            access-key-id: LTAI5tH3TMdoWtXTXv6CZ8xu
#            access-key-secret: gAaG2PbsX4uub7vofD6yN4ILmuEDmS
      server:
        share-prefix: https://driveharbor.com/share/
      bloom:
        filter:
          local:
            items:
              - name: SHARE_SIMPLE_DETAIL
                funnel-type-name: LONG
                expected-insertions: 10000000
                fpp: 0.01